"""entity_trending

Revision ID: 205cd471590b
Revises: b74cf0a0b7c0
Create Date: 2026-08-12 12:35:04.605289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205cd471590b'
down_revision: Union[str, None] = 'b74cf0a0b7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('trending_news_counts',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['trending_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'hour_bucket')
    )
    op.create_table('trending_query_counts',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['trending_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'hour_bucket')
    )
    op.create_table('article_entities',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['trending_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_entities')
    op.drop_table('trending_query_counts')
    op.drop_table('trending_news_counts')
    op.drop_table('trending_entities')
    # ### end Alembic commands ###
